#!/bin/sh

# Saves the default led0 trigger to /run/piaware-ble-connect/trigger
triggerfile=""
if [ -e "/sys/class/leds/led0/trigger" ]; then
  triggerfile="/sys/class/leds/led0/trigger"
elif [ -e "/sys/class/leds/ACT/trigger" ]; then
  triggerfile="/sys/class/leds/ACT/trigger"
else
  exit 1
fi

trigger=$(awk -F '[][]' '{print $2}' $triggerfile)
echo -n $trigger > '/run/piaware-ble-connect/trigger'
